const S={projectPath:'',projectName:'',assets:{},doc:{version:'0.1b',project_name:'',scenes:[]},bg:null,scene:null,sel:null,nw:0,nh:0,dw:0,dh:0,zoom:1,mode:'idle',drag:null,dirty:false,save:'saved',undo:[],redo:[]};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const E={form:$('#scan-form'),path:$('#project-path'),scan:$('#scan-button'),save:$('#save-hotspots-button'),exportBtn:$('#export-hotspots-button'),checkBtn:$('#check-hotspots-button'),inspectBtn:$('#inspect-resources-button'),saveStatus:$('#save-status'),exportStatus:$('#export-status'),checkSummary:$('#check-summary'),checkList:$('#check-list'),templatePreview:$('#template-preview'),resourceSummary:$('#resource-summary'),resourceStats:$('#resource-stats'),resourceNaming:$('#resource-naming'),resourceMissing:$('#resource-missing'),resourceUnused:$('#resource-unused'),resourcePreview:$('#resource-preview'),git:$('#git-chip'),project:$('#project-status'),tabs:$('#asset-tabs'),count:$('#asset-count'),assets:$('#asset-list'),bgName:$('#selected-background'),mouse:$('#mouse-position'),scale:$('#canvas-scale'),empty:$('#canvas-empty'),scroll:$('#canvas-scroll'),wrap:$('#canvas-wrap'),img:$('#background-preview'),layer:$('#hotspot-layer'),list:$('#hotspot-list'),form2:$('#hotspot-form'),hid:$('#hotspot-id-hidden'),id:$('#hotspot-id'),name:$('#hotspot-name'),target:$('#hotspot-target'),tip:$('#hotspot-tooltip'),x:$('#hotspot-x'),y:$('#hotspot-y'),w:$('#hotspot-w'),h:$('#hotspot-h'),enabled:$('#hotspot-enabled'),apply:$('#apply-hotspot-button'),del:$('#delete-hotspot-button'),dup:$('#duplicate-hotspot-button'),up:$('#move-up-button'),down:$('#move-down-button'),undo:$('#undo-button'),redo:$('#redo-button'),log:$('#scan-log')};
const labels={backgrounds:'BG',characters:'Char',ui:'UI',audio:'Audio'};let cat='backgrounds';
E.form.addEventListener('submit',async e=>{e.preventDefault();await scan(E.path.value.trim())});E.save.addEventListener('click',save);E.checkBtn.addEventListener('click',runChecks);E.inspectBtn.addEventListener('click',inspectResources);E.exportBtn.addEventListener('click',exportHotspots);E.form2.addEventListener('submit',e=>{e.preventDefault();hist();syncForm();log('form applied')});E.del.addEventListener('click',delSel);E.dup.addEventListener('click',dupSel);E.up.addEventListener('click',()=>moveLayer(-1));E.down.addEventListener('click',()=>moveLayer(1));E.undo.addEventListener('click',undo);E.redo.addEventListener('click',redo);$$('.zoom-button').forEach(b=>b.addEventListener('click',()=>setZoom(+b.dataset.zoom)));
[E.id,E.name,E.target,E.tip,E.enabled].forEach(i=>i.addEventListener('change',()=>{hist();syncForm()}));[E.x,E.y,E.w,E.h].forEach(i=>{i.addEventListener('change',()=>{hist();syncForm()});i.addEventListener('input',syncForm)});
E.img.addEventListener('load',()=>{S.nw=E.img.naturalWidth;S.nh=E.img.naturalHeight;applyZoom();draw()});E.wrap.addEventListener('pointerdown',down);E.wrap.addEventListener('pointermove',move);E.wrap.addEventListener('pointerup',up);E.wrap.addEventListener('pointercancel',up);E.wrap.addEventListener('pointerleave',mouse);E.scroll.addEventListener('wheel',wheel,{passive:false});window.addEventListener('resize',()=>{metrics();draw()});document.addEventListener('keydown',keys);$$('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));
function route(name){let page=name||'dashboard';$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));$$('.primary-nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===page));let inspector=['dashboard','hotspot-editor','assets'].includes(page)?page:'placeholder';$$('.inspector-block').forEach(b=>b.classList.toggle('hidden',b.dataset.inspector!==inspector));if(page==='hotspot-editor'){setTimeout(()=>{metrics();draw()},0)}}
function dashScan(j){let total=Object.values(j.assets?.categories||{}).reduce((a,b)=>a+b.length,0);let n=$('#dashboard-project-name'),p=$('#dashboard-project-path'),c=$('#dashboard-project-chip'),a=$('#dashboard-assets-total');if(n)n.textContent=S.projectName;if(p)p.textContent=S.projectPath;if(c)c.textContent=j.git?.clean?'Project clean':'Project scanned';if(a)a.textContent=total}
function dashResources(s){let m=$('#dashboard-missing-count'),u=$('#dashboard-unused-count');if(m)m.textContent=s.missing_references;if(u)u.textContent=s.unused_resources}
function dashHotspots(s){let h=$('#dashboard-hotspot-ok');if(h)h.textContent=`${s.ok}/${s.total}`}
async function scan(p){if(!p)return log('enter path');setLoad(1);E.log.textContent='scanning...';try{let r=await fetch('/api/project/open',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:p})}),j=await r.json();if(!r.ok)throw Error(j.detail||'scan failed');summary(j);await loadHotspots();setSave('saved')}catch(e){log('scan failed: '+e.message)}finally{setLoad(0)}}
function summary(j){S.projectPath=j.project_path||'';S.projectName=S.projectPath.split(/[\\/]/).filter(Boolean).pop()||'Project';S.assets=j.assets?.categories||{};S.bg=null;S.scene=null;S.sel=null;S.doc={version:'0.1b',project_name:S.projectName,scenes:[]};S.zoom=1;S.dirty=false;S.undo=[];S.redo=[];E.project.innerHTML=[row('script',badge(j.checks?.script_rpy)),row('gui',badge(j.checks?.gui_rpy)),row('options',badge(j.checks?.options_rpy)),row('gitignore',badge(j.checks?.gitignore))].join('');E.git.textContent=j.git?.is_repository?`Git: ${j.git.branch} · ${j.git.clean?'clean':'dirty'} · ${j.git.latest_commit}`:'Git: none';dashScan(j);tabs();assets(cat);clearCanvas();hotList();ui();E.log.textContent=(j.logs||[]).join('\n')||'done'}
async function loadHotspots(){let r=await fetch('/api/hotspots');if(!r.ok)throw Error('hotspots load failed');S.doc=await r.json();S.doc.project_name||=S.projectName;S.doc.scenes||=[];S.undo=[snap()];S.redo=[];ui()}
function tabs(){let total=Object.values(S.assets).reduce((a,b)=>a+b.length,0);E.count.textContent=total+' assets';E.tabs.innerHTML=Object.keys(labels).map(k=>`<button class="asset-tab${k===cat?' active':''}" data-category="${k}">${labels[k]} (${S.assets[k]?.length||0})</button>`).join('');$$('[data-category]',E.tabs).forEach(b=>b.onclick=()=>{cat=b.dataset.category;tabs();assets(cat)})}
function assets(k){let a=S.assets[k]||[];if(!a.length){E.assets.textContent='no assets';return}E.assets.innerHTML=a.map(it=>`<div class="asset-row${it.relative_path===S.bg?' selected':''}"><div><strong>${esc(it.name)}</strong><small>${esc(it.relative_path)} · ${fmt(it.size_bytes)}</small></div>${k==='backgrounds'?`<button class="mini-button" data-bg="${esc(it.relative_path)}">open</button>`:''}</div>`).join('');$$('[data-bg]',E.assets).forEach(b=>b.onclick=()=>openBg(b.dataset.bg))}
function openBg(p){S.bg=p;S.scene=scene(p);S.sel=null;E.bgName.textContent=p;E.empty.classList.add('hidden');E.scroll.classList.remove('hidden');E.img.src='/api/assets/file?path='+encodeURIComponent(p);assets(cat);fill(null);hotList();ui()}
function clearCanvas(){E.bgName.textContent='no background';E.empty.classList.remove('hidden');E.scroll.classList.add('hidden');E.layer.innerHTML='';E.mouse.textContent='mouse:-';E.scale.textContent='zoom:-'}
function scene(p){let s=S.doc.scenes.find(x=>x.background===p);if(!s){s={scene_id:'scene_'+p.split('/').pop().replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_]+/g,'_'),background:p,hotspots:[]};S.doc.scenes.push(s);dirty()}return s}
function applyZoom(){if(!S.nw)return;E.img.style.width=Math.round(S.nw*S.zoom)+'px';E.img.style.height='auto';metrics();$$('.zoom-button').forEach(b=>b.classList.toggle('active',Math.abs(+b.dataset.zoom-S.zoom)<.001))}
function setZoom(z,center=false){let old=S.zoom;S.zoom=Math.max(.25,Math.min(2,z));let sx=0,sy=0;if(center){sx=(E.scroll.scrollLeft+E.scroll.clientWidth/2)/old;sy=(E.scroll.scrollTop+E.scroll.clientHeight/2)/old}applyZoom();draw();if(center){E.scroll.scrollLeft=sx*S.zoom-E.scroll.clientWidth/2;E.scroll.scrollTop=sy*S.zoom-E.scroll.clientHeight/2}}
function wheel(e){if(!e.ctrlKey)return;e.preventDefault();setZoom(S.zoom+(e.deltaY<0?.25:-.25),true)}
function metrics(){let r=E.img.getBoundingClientRect();S.dw=r.width;S.dh=r.height;if(S.nw&&S.dw)E.scale.textContent=`zoom:${Math.round(S.zoom*100)}% scale:${gx().toFixed(3)}/${gy().toFixed(3)}`}
function draw(){if(!S.scene||!S.dw)return;metrics();E.layer.innerHTML='';S.scene.hotspots.forEach((h,i)=>{if(!h.enabled)return;let b=document.createElement('div');b.className='hotspot-box'+(h.id===S.sel?' selected flash':'');b.dataset.hotspotId=h.id;b.style.zIndex=i+1;b.style.left=h.x/gx()+'px';b.style.top=h.y/gy()+'px';b.style.width=h.w/gx()+'px';b.style.height=h.h/gy()+'px';b.innerHTML=`<span>${esc(h.name||h.id)}</span><i class="resize-handle"></i>`;E.layer.appendChild(b)})}
function hotList(){if(!S.scene){E.list.textContent='select background';return}let hs=S.scene.hotspots;if(!hs.length){E.list.textContent='no hotspots';return}E.list.innerHTML=hs.map((h,i)=>`<button class="hotspot-list-item${h.id===S.sel?' selected':''}" data-id="${esc(h.id)}"><strong>${i+1}. ${esc(h.id)}</strong><span>${esc(h.name)} · x:${h.x} y:${h.y} w:${h.w} h:${h.h}</span></button>`).join('');$$('[data-id]',E.list).forEach(b=>b.onclick=()=>select(b.dataset.id,true))}
function down(e){if(!S.scene||e.button!==0)return;metrics();let p=pt(e),box=e.target.closest?.('.hotspot-box'),handle=e.target.closest?.('.resize-handle');if(box){let h=find(box.dataset.hotspotId);if(!h)return;hist();select(h.id);e.preventDefault();E.wrap.setPointerCapture(e.pointerId);S.drag={start:p,orig:{...h},id:h.id};S.mode=handle?'resizing':'moving';return}hist();e.preventDefault();E.wrap.setPointerCapture(e.pointerId);let h={id:nextId(),name:'new hotspot',target_label:'',tooltip:'',x:Math.round(p.x),y:Math.round(p.y),w:1,h:1,enabled:true};S.scene.hotspots.push(h);S.drag={start:p,id:h.id};S.mode='drawing';select(h.id);dirty()}
function move(e){mouse(e);if(S.mode==='idle'||!S.drag)return;let p=pt(e),h=find(S.drag.id);if(!h)return;if(S.mode==='drawing'){h.x=Math.round(Math.min(S.drag.start.x,p.x));h.y=Math.round(Math.min(S.drag.start.y,p.y));h.w=Math.max(1,Math.round(Math.abs(p.x-S.drag.start.x)));h.h=Math.max(1,Math.round(Math.abs(p.y-S.drag.start.y)))}else if(S.mode==='moving'){let o=S.drag.orig;h.x=clamp(Math.round(o.x+p.x-S.drag.start.x),0,S.nw-h.w);h.y=clamp(Math.round(o.y+p.y-S.drag.start.y),0,S.nh-h.h)}else{let o=S.drag.orig;h.w=Math.max(1,Math.round(o.w+p.x-S.drag.start.x));h.h=Math.max(1,Math.round(o.h+p.y-S.drag.start.y))}fill(h);draw();hotList();dirty()}
function up(e){if(S.mode!=='idle'){try{E.wrap.releasePointerCapture(e.pointerId)}catch{}}let h=find(S.drag?.id);if(S.mode==='drawing'&&h&&(h.w<3||h.h<3))remove(h.id);S.mode='idle';S.drag=null;draw();hotList()}
function pt(e){let r=E.img.getBoundingClientRect(),dx=clamp(e.clientX-r.left,0,r.width),dy=clamp(e.clientY-r.top,0,r.height);return{x:dx*gx(),y:dy*gy()}}
function mouse(e){if(!S.bg||!S.dw){E.mouse.textContent='mouse:-';return}let p=pt(e);E.mouse.textContent=`mouse:${Math.round(p.x)},${Math.round(p.y)}`}
function select(id,focus=false){let h=find(id);if(!h)return;S.sel=id;fill(h);ui();draw();hotList();if(focus){let box=$(`.hotspot-box[data-hotspot-id="${CSS.escape(id)}"]`);box?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'})}}
function fill(h){E.hid.value=h?.id||'';E.id.value=h?.id||'';E.name.value=h?.name||'';E.target.value=h?.target_label||'';E.tip.value=h?.tooltip||'';E.x.value=h?.x??0;E.y.value=h?.y??0;E.w.value=h?.w??100;E.h.value=h?.h??100;E.enabled.checked=h?.enabled??true}
function syncForm(){let h=find(S.sel);if(!h)return;let old=h.id,nid=uniqueId(E.id.value.trim()||old,old);h.id=nid;h.name=E.name.value.trim()||'new hotspot';h.target_label=E.target.value.trim();h.tooltip=E.tip.value.trim();h.x=Math.max(0,num(E.x,h.x));h.y=Math.max(0,num(E.y,h.y));h.w=Math.max(1,num(E.w,h.w));h.h=Math.max(1,num(E.h,h.h));h.enabled=E.enabled.checked;S.sel=nid;fill(h);draw();hotList();dirty()}
function delSel(){if(!S.sel)return;hist();remove(S.sel);S.sel=null;fill(null);draw();hotList();dirty();ui()}
function dupSel(){let h=find(S.sel);if(!h)return;hist();let c={...h,id:nextId(),name:(h.name||'hotspot')+' copy',x:h.x+20,y:h.y+20};S.scene.hotspots.push(c);select(c.id,true);dirty()}
function moveLayer(d){if(!S.sel||!S.scene)return;let a=S.scene.hotspots,i=a.findIndex(h=>h.id===S.sel),j=i+d;if(i<0||j<0||j>=a.length)return;hist();[a[i],a[j]]=[a[j],a[i]];draw();hotList();dirty()}
async function save(){try{validate();setSave('saving');let r=await fetch('/api/hotspots/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(S.doc)}),j=await r.json();if(!r.ok)throw Error(j.detail||'save failed');S.doc=j;S.undo=[snap()];S.redo=[];setSave('saved');log('saved tools_data/hotspots.json')}catch(e){setSave('failed');log('save failed: '+e.message)}}
async function exportHotspots(){try{let c=await runChecks();if(c&&!c.ok)log('warning: hotspot check has issues before export');E.exportBtn.disabled=true;E.exportStatus.textContent='Export: exporting...';let r=await fetch('/api/export/hotspots',{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.detail||'export failed');E.exportStatus.textContent=`Export: ${j.scene_count} screens / ${j.hotspot_count} buttons`;log(`exported ${j.output_path}`)}catch(e){E.exportStatus.textContent='Export: failed';log('export failed: '+e.message)}finally{ui()}}
async function runChecks(){try{let r=await fetch('/api/hotspots/check'),j=await r.json();if(!r.ok)throw Error(j.detail||'check failed');renderCheck(j);dashHotspots(j.summary);let tr=await fetch('/api/hotspots/label-templates'),tj=await tr.json();if(tr.ok)renderTemplates(tj);log(`check: ok=${j.summary.ok} missing=${j.summary.missing} empty=${j.summary.empty} invalid=${j.summary.invalid} disabled=${j.summary.disabled}`);return j}catch(e){E.checkSummary.textContent='Check failed';E.checkList.textContent=e.message;log('check failed: '+e.message);return null}}
function renderCheck(j){let s=j.summary;E.checkSummary.textContent=`total ${s.total} / ok ${s.ok} / missing ${s.missing} / empty ${s.empty} / invalid ${s.invalid} / disabled ${s.disabled}`;E.checkList.classList.remove('empty');E.checkList.innerHTML=(j.items||[]).map(i=>`<div class="check-item ${i.status}"><strong>${esc(i.status)}</strong><span>${esc(i.hotspot_id)} -> ${esc(i.target_label||'(empty)')}</span><small>${esc(i.message)} · suggest: ${esc(i.suggested_label)}</small></div>`).join('')||'no hotspots'}
function renderTemplates(j){E.templatePreview.textContent=(j.templates||[]).map(t=>t.template).join('\n')||'No missing label templates.'}
async function inspectResources(){try{let r=await fetch('/api/resources/inspect'),j=await r.json();if(!r.ok)throw Error(j.detail||'resource inspect failed');renderResources(j);dashResources(j.summary);log(`resources: total=${j.summary.total} naming=${j.summary.naming_warnings} missing=${j.summary.missing_references} unused=${j.summary.unused_resources}`);return j}catch(e){E.resourceSummary.textContent='Resource check failed';E.resourceStats.textContent=e.message;log('resource inspect failed: '+e.message);return null}}
function renderResources(j){let s=j.summary;E.resourceSummary.textContent=`total ${s.total} / naming ${s.naming_warnings} / missing ${s.missing_references} / unused ${s.unused_resources}`;E.resourceStats.classList.remove('empty');E.resourceStats.innerHTML=`<span>BG ${s.backgrounds}</span><span>Char ${s.characters}</span><span>UI ${s.ui}</span><span>Audio ${s.audio}</span><span>Other Images ${s.other_images}</span>`;E.resourceNaming.innerHTML=renderResourceIssues(j.naming_issues,'warning');E.resourceMissing.innerHTML=(j.missing_references||[]).map(i=>`<div class="resource-item missing"><strong>${esc(i.reference)}</strong><small>${esc(i.file)}:${i.line}</small></div>`).join('')||'No missing references.';E.resourceUnused.innerHTML=(j.unused_resources||[]).slice(0,120).map(i=>renderResource(i.resource,'unused')).join('')||'No unused resources.';$$('[data-preview]',E.resourceUnused).forEach(b=>b.onclick=()=>previewResource(b.dataset.preview));$$('[data-preview]',E.resourceNaming).forEach(b=>b.onclick=()=>previewResource(b.dataset.preview))}
function renderResourceIssues(items){return(items||[]).slice(0,120).map(i=>`<div class="resource-item warning"><strong>${esc(i.code)}</strong><span>${esc(i.resource.relative_path)}</span><small>${esc(i.message)}</small>${i.resource.is_image?`<button class="mini-button" data-preview="${esc(i.resource.relative_path)}">preview</button>`:''}</div>`).join('')||'No naming warnings.'}
function renderResource(r,cls){return`<div class="resource-item ${cls}"><strong>${esc(r.category)}</strong><span>${esc(r.relative_path)}</span><small>${fmt(r.size_bytes)}</small>${r.is_image?`<button class="mini-button" data-preview="${esc(r.relative_path)}">preview</button>`:''}</div>`}
function previewResource(path){E.resourcePreview.classList.remove('empty');E.resourcePreview.innerHTML=`<img src="/api/assets/file?path=${encodeURIComponent(path)}" alt="resource preview"><small>${esc(path)}</small>`}
function validate(){for(let sc of S.doc.scenes){if(!sc.background||sc.background.includes('..')||/^[a-zA-Z]:/.test(sc.background))throw Error('bad background');let ids=new Set;for(let h of sc.hotspots){if(!h.id)throw Error('empty id');if(ids.has(h.id))throw Error('duplicate id '+h.id);ids.add(h.id);if(![h.x,h.y,h.w,h.h].every(Number.isFinite))throw Error('bad coords');if(h.w<=0||h.h<=0)throw Error('bad size')}}}
function hist(){let s=snap();if(S.undo[S.undo.length-1]!==s){S.undo.push(s);if(S.undo.length>80)S.undo.shift()}S.redo=[];ui()}
function snap(){return JSON.stringify({doc:S.doc,bg:S.bg,sel:S.sel})}
function restore(s){let o=JSON.parse(s);S.doc=o.doc;S.bg=o.bg;S.sel=o.sel;S.scene=S.bg?scene(S.bg):null;if(S.bg){E.img.src='/api/assets/file?path='+encodeURIComponent(S.bg);E.bgName.textContent=S.bg}fill(find(S.sel));draw();hotList();ui();dirty()}
function undo(){if(S.undo.length<2)return;S.redo.push(S.undo.pop());restore(S.undo[S.undo.length-1]);log('undo')}
function redo(){if(!S.redo.length)return;let s=S.redo.pop();S.undo.push(s);restore(s);log('redo')}
function keys(e){if(e.ctrlKey&&(e.key==='+'||e.key==='=')){e.preventDefault();setZoom(S.zoom+.25,true)}else if(e.ctrlKey&&e.key==='-'){e.preventDefault();setZoom(S.zoom-.25,true)}else if(e.ctrlKey&&e.key==='0'){e.preventDefault();setZoom(1,true)}else if(e.ctrlKey&&e.key.toLowerCase()==='z'&&e.shiftKey){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='d'){e.preventDefault();dupSel()}else if(e.key==='Delete'){e.preventDefault();delSel()}else if(e.key==='Escape'){S.sel=null;fill(null);draw();hotList();ui()}}
function find(id){return id&&S.scene?S.scene.hotspots.find(h=>h.id===id):null}
function remove(id){if(S.scene)S.scene.hotspots=S.scene.hotspots.filter(h=>h.id!==id)}
function nextId(){return uniqueId('hotspot_'+String((S.scene?.hotspots.length||0)+1).padStart(3,'0'))}
function uniqueId(base,allow=null){let ids=new Set((S.scene?.hotspots||[]).map(h=>h.id));let b=base||'hotspot';if(!ids.has(b)||b===allow)return b;let i=2;while(ids.has(`${b}_${i}`))i++;return `${b}_${i}`}
function dirty(){S.dirty=true;setSave('unsaved');ui()}
function setSave(v){S.save=v;S.dirty=v==='unsaved';E.saveStatus.className='save-status '+v;E.saveStatus.textContent={saved:'Saved',unsaved:'Unsaved',saving:'Saving...',failed:'Save failed'}[v]||v;ui()}
function ui(){let has=!!S.sel,scene=!!S.scene;E.save.disabled=!scene;E.checkBtn.disabled=!S.projectPath;E.inspectBtn.disabled=!S.projectPath;E.exportBtn.disabled=!S.projectPath;E.apply.disabled=!has;E.del.disabled=!has;E.dup.disabled=!has;E.up.disabled=!has;E.down.disabled=!has;E.undo.disabled=S.undo.length<2;E.redo.disabled=!S.redo.length;E.save.textContent=S.save==='unsaved'?'保存 hotspots.json *':'保存 hotspots.json'}
function row(a,b){return `<div class="status-row"><span>${a}</span><strong>${b}</strong></div>`}
function badge(v){return `<span class="badge ${v?'ok':'bad'}">${v?'OK':'MISS'}</span>`}
function log(t){E.log.textContent=`${E.log.textContent}\n${t}`.trim()}
function setLoad(v){E.scan.disabled=v;E.scan.textContent=v?'扫描中...':'扫描'}
function gx(){return S.dw?S.nw/S.dw:1}function gy(){return S.dh?S.nh/S.dh:1}
function num(i,f){let v=Number(i.value);return Number.isFinite(v)?Math.round(v):f}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function fmt(n){if(!Number.isFinite(n)||n<=0)return'0 B';let u=['B','KB','MB','GB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
