const S={projectPath:'',projectName:'',assets:{},doc:{version:'0.1b',project_name:'',scenes:[]},bg:null,scene:null,sel:null,nw:0,nh:0,dw:0,dh:0,zoom:1,mode:'idle',drag:null,dirty:false,save:'saved',undo:[],redo:[],resourceData:null,resourceFilter:'all',resourceSelected:null,labelGraph:null,labelFilter:'all',labelStatusFilter:'all',labelEdgeFilter:'all',labelSearch:'',labelSelected:null,labelDetail:null,labelNeighborMode:false,labelGraphZoom:1,labelGraphPan:{x:0,y:0},labelGraphDrag:null,labelGraphNodes:[]};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const E={form:$('#scan-form'),path:$('#project-path'),scan:$('#scan-button'),save:$('#save-hotspots-button'),exportBtn:$('#export-hotspots-button'),checkBtn:$('#check-hotspots-button'),inspectBtn:$('#inspect-resources-button'),saveStatus:$('#save-status'),exportStatus:$('#export-status'),checkSummary:$('#check-summary'),checkList:$('#check-list'),templatePreview:$('#template-preview'),resourceSummary:$('#resource-summary'),resourceStats:$('#resource-stats'),resourceNaming:$('#resource-naming'),resourceMissing:$('#resource-missing'),resourceUnused:$('#resource-unused'),resourcePreview:$('#resource-preview'),resourceList:$('#resource-list'),resourceListCount:$('#resource-list-count'),resourceDetail:$('#resource-detail'),resourceFilters:$('#resource-filters'),labelGraphSummary:$('#label-graph-summary'),labelHealthCards:$('#label-health-cards'),labelLoad:$('#load-label-graph-button'),labelSearch:$('#label-search'),labelList:$('#label-list'),labelEdges:$('#label-edge-list'),labelMissing:$('#label-missing-list'),labelUnused:$('#label-unused-list'),labelDetail:$('#label-detail'),labelGraphCanvas:$('#label-graph-canvas'),labelGraphSvg:$('#label-graph-svg'),labelGraphFit:$('#label-graph-fit'),labelGraphZoomIn:$('#label-graph-zoom-in'),labelGraphZoomOut:$('#label-graph-zoom-out'),labelGraphVisible:$('#label-graph-visible-count'),labelShowNeighbors:$('#label-show-neighbors'),labelShowAll:$('#label-show-all'),labelFixSuggestions:$('#label-fix-suggestions'),git:$('#git-chip'),project:$('#project-status'),tabs:$('#asset-tabs'),count:$('#asset-count'),assets:$('#asset-list'),bgName:$('#selected-background'),mouse:$('#mouse-position'),scale:$('#canvas-scale'),empty:$('#canvas-empty'),scroll:$('#canvas-scroll'),wrap:$('#canvas-wrap'),img:$('#background-preview'),layer:$('#hotspot-layer'),list:$('#hotspot-list'),form2:$('#hotspot-form'),hid:$('#hotspot-id-hidden'),id:$('#hotspot-id'),name:$('#hotspot-name'),target:$('#hotspot-target'),tip:$('#hotspot-tooltip'),x:$('#hotspot-x'),y:$('#hotspot-y'),w:$('#hotspot-w'),h:$('#hotspot-h'),enabled:$('#hotspot-enabled'),apply:$('#apply-hotspot-button'),del:$('#delete-hotspot-button'),dup:$('#duplicate-hotspot-button'),up:$('#move-up-button'),down:$('#move-down-button'),undo:$('#undo-button'),redo:$('#redo-button'),log:$('#scan-log')};
const labels={backgrounds:'BG',characters:'Char',ui:'UI',audio:'Audio'};let cat='backgrounds';
E.form.addEventListener('submit',async e=>{e.preventDefault();await scan(E.path.value.trim())});E.save.addEventListener('click',save);E.checkBtn.addEventListener('click',runChecks);E.inspectBtn.addEventListener('click',inspectResources);E.exportBtn.addEventListener('click',exportHotspots);E.form2.addEventListener('submit',e=>{e.preventDefault();hist();syncForm();log('form applied')});E.del.addEventListener('click',delSel);E.dup.addEventListener('click',dupSel);E.up.addEventListener('click',()=>moveLayer(-1));E.down.addEventListener('click',()=>moveLayer(1));E.undo.addEventListener('click',undo);E.redo.addEventListener('click',redo);$$('.zoom-button').forEach(b=>b.addEventListener('click',()=>setZoom(+b.dataset.zoom)));
[E.id,E.name,E.target,E.tip,E.enabled].forEach(i=>i.addEventListener('change',()=>{hist();syncForm()}));[E.x,E.y,E.w,E.h].forEach(i=>{i.addEventListener('change',()=>{hist();syncForm()});i.addEventListener('input',syncForm)});
E.img.addEventListener('load',()=>{S.nw=E.img.naturalWidth;S.nh=E.img.naturalHeight;applyZoom();draw()});E.wrap.addEventListener('pointerdown',down);E.wrap.addEventListener('pointermove',move);E.wrap.addEventListener('pointerup',up);E.wrap.addEventListener('pointercancel',up);E.wrap.addEventListener('pointerleave',mouse);E.scroll.addEventListener('wheel',wheel,{passive:false});window.addEventListener('resize',()=>{metrics();draw()});document.addEventListener('keydown',keys);$$('[data-route]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.route)));$$('[data-resource-filter]').forEach(b=>b.addEventListener('click',()=>setResourceFilter(b.dataset.resourceFilter)));E.labelLoad?.addEventListener('click',loadLabelGraph);E.labelSearch?.addEventListener('input',()=>{S.labelSearch=E.labelSearch.value.trim().toLowerCase();renderLabelList();renderLabelGraphSvg()});$$('[data-label-filter]').forEach(b=>b.addEventListener('click',()=>setLabelFilter(b.dataset.labelFilter)));$$('[data-label-status]').forEach(b=>b.addEventListener('click',()=>setLabelStatusFilter(b.dataset.labelStatus)));$$('[data-edge-filter]').forEach(b=>b.addEventListener('click',()=>setLabelEdgeFilter(b.dataset.edgeFilter)));E.labelShowNeighbors?.addEventListener('click',()=>{S.labelNeighborMode=true;renderLabelList();renderLabelGraphSvg()});E.labelShowAll?.addEventListener('click',()=>{S.labelNeighborMode=false;renderLabelList();renderLabelGraphSvg()});E.labelGraphFit?.addEventListener('click',fitLabelGraph);E.labelGraphZoomIn?.addEventListener('click',()=>zoomLabelGraph(1.18));E.labelGraphZoomOut?.addEventListener('click',()=>zoomLabelGraph(.85));E.labelGraphCanvas?.addEventListener('pointerdown',startLabelGraphPan);E.labelGraphCanvas?.addEventListener('pointermove',moveLabelGraphPan);E.labelGraphCanvas?.addEventListener('pointerup',endLabelGraphPan);E.labelGraphCanvas?.addEventListener('pointerleave',endLabelGraphPan);
function route(name){let page=name||'dashboard';$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));let activeSet=false;$$('.primary-nav-item').forEach(b=>{let on=!activeSet&&b.dataset.route===page;b.classList.toggle('active',on);if(on)activeSet=true});let inspector=['dashboard','hotspot-editor','assets','labels'].includes(page)?page:'placeholder';$$('.inspector-block').forEach(b=>b.classList.toggle('hidden',b.dataset.inspector!==inspector));if(page==='hotspot-editor'){setTimeout(()=>{metrics();draw()},0)}}
function dashScan(j){let total=Object.values(j.assets?.categories||{}).reduce((a,b)=>a+b.length,0);let n=$('#dashboard-project-name'),p=$('#dashboard-project-path'),c=$('#dashboard-project-chip'),a=$('#dashboard-assets-total');if(n)n.textContent=S.projectName;if(p)p.textContent=S.projectPath;if(c)c.textContent=j.git?.clean?'Project clean':'Project scanned';if(a)a.textContent=total}
function dashResources(s){let m=$('#dashboard-missing-count'),u=$('#dashboard-unused-count');if(m)m.textContent=s.missing_references;if(u)u.textContent=s.unused_resources}
function dashHotspots(s){let h=$('#dashboard-hotspot-ok');if(h)h.textContent=`${s.ok}/${s.total}`}
async function scan(p){if(!p)return log('enter path');setLoad(1);E.log.textContent='scanning...';try{let r=await fetch('/api/project/open',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:p})}),j=await r.json();if(!r.ok)throw Error(j.detail||'scan failed');summary(j);await loadHotspots();setSave('saved')}catch(e){log('scan failed: '+e.message)}finally{setLoad(0)}}
function summary(j){S.projectPath=j.project_path||'';S.projectName=S.projectPath.split(/[\\/]/).filter(Boolean).pop()||'Project';S.assets=j.assets?.categories||{};S.bg=null;S.scene=null;S.sel=null;S.doc={version:'0.1b',project_name:S.projectName,scenes:[]};S.zoom=1;S.dirty=false;S.undo=[];S.redo=[];E.project.innerHTML=[row('script',badge(j.checks?.script_rpy)),row('gui',badge(j.checks?.gui_rpy)),row('options',badge(j.checks?.options_rpy)),row('gitignore',badge(j.checks?.gitignore))].join('');E.git.textContent=j.git?.is_repository?`Git: ${j.git.branch} 路 ${j.git.clean?'clean':'dirty'} 路 ${j.git.latest_commit}`:'Git: none';dashScan(j);tabs();assets(cat);clearCanvas();hotList();ui();E.log.textContent=(j.logs||[]).join('\n')||'done'}
async function loadHotspots(){let r=await fetch('/api/hotspots');if(!r.ok)throw Error('hotspots load failed');S.doc=await r.json();S.doc.project_name||=S.projectName;S.doc.scenes||=[];S.undo=[snap()];S.redo=[];ui()}
function tabs(){let total=Object.values(S.assets).reduce((a,b)=>a+b.length,0);E.count.textContent=total+' assets';E.tabs.innerHTML=Object.keys(labels).map(k=>`<button class="asset-tab${k===cat?' active':''}" data-category="${k}">${labels[k]} (${S.assets[k]?.length||0})</button>`).join('');$$('[data-category]',E.tabs).forEach(b=>b.onclick=()=>{cat=b.dataset.category;tabs();assets(cat)})}
function assets(k){let a=S.assets[k]||[];if(!a.length){E.assets.textContent='no assets';return}E.assets.innerHTML=a.map(it=>assetCard(it,k)).join('');$$('[data-bg]',E.assets).forEach(b=>b.onclick=()=>openBg(b.dataset.bg))}
function assetCard(it,k){let selected=it.relative_path===S.bg?' selected':'',isAudio=k==='audio',src=isAudio?'':`/api/assets/file?path=${encodeURIComponent(it.relative_path)}`;return`<div class="asset-row asset-card${selected}" ${k==='backgrounds'?`data-bg="${esc(it.relative_path)}"`:''} title="${esc(it.relative_path)}"><div class="asset-thumb ${isAudio?'audio':''}">${isAudio?'♪':`<img src="${src}" alt="${esc(it.name)}" loading="lazy">`}</div><div class="asset-meta"><strong title="${esc(it.name)}">${esc(it.name)}</strong><small title="${esc(it.relative_path)}">${esc(it.relative_path)}</small><div class="asset-subline"><span>${esc(k)}</span><em>${fmt(it.size_bytes)}</em></div></div></div>`}
function openBg(p){S.bg=p;S.scene=scene(p);S.sel=null;E.bgName.textContent=p;E.empty.classList.add('hidden');E.scroll.classList.remove('hidden');E.img.src='/api/assets/file?path='+encodeURIComponent(p);assets(cat);fill(null);hotList();ui()}
function clearCanvas(){E.bgName.textContent='no background';E.empty.classList.remove('hidden');E.scroll.classList.add('hidden');E.layer.innerHTML='';E.mouse.textContent='mouse:-';E.scale.textContent='zoom:-'}
function scene(p){let s=S.doc.scenes.find(x=>x.background===p);if(!s){s={scene_id:'scene_'+p.split('/').pop().replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_]+/g,'_'),background:p,hotspots:[]};S.doc.scenes.push(s);dirty()}return s}
function applyZoom(){if(!S.nw)return;E.img.style.width=Math.round(S.nw*S.zoom)+'px';E.img.style.height='auto';metrics();$$('.zoom-button').forEach(b=>b.classList.toggle('active',Math.abs(+b.dataset.zoom-S.zoom)<.001))}
function setZoom(z,center=false){let old=S.zoom;S.zoom=Math.max(.25,Math.min(2,z));let sx=0,sy=0;if(center){sx=(E.scroll.scrollLeft+E.scroll.clientWidth/2)/old;sy=(E.scroll.scrollTop+E.scroll.clientHeight/2)/old}applyZoom();draw();if(center){E.scroll.scrollLeft=sx*S.zoom-E.scroll.clientWidth/2;E.scroll.scrollTop=sy*S.zoom-E.scroll.clientHeight/2}}
function wheel(e){if(!e.ctrlKey)return;e.preventDefault();setZoom(S.zoom+(e.deltaY<0?.25:-.25),true)}
function metrics(){let r=E.img.getBoundingClientRect();S.dw=r.width;S.dh=r.height;if(S.nw&&S.dw)E.scale.textContent=`zoom:${Math.round(S.zoom*100)}% scale:${gx().toFixed(3)}/${gy().toFixed(3)}`}
function draw(){if(!S.scene||!S.dw)return;metrics();E.layer.innerHTML='';S.scene.hotspots.forEach((h,i)=>{if(!h.enabled)return;let b=document.createElement('div');b.className='hotspot-box'+(h.id===S.sel?' selected flash':'');b.dataset.hotspotId=h.id;b.style.zIndex=i+1;b.style.left=h.x/gx()+'px';b.style.top=h.y/gy()+'px';b.style.width=h.w/gx()+'px';b.style.height=h.h/gy()+'px';b.innerHTML=`<span>${esc(h.name||h.id)}</span><i class="resize-handle"></i>`;E.layer.appendChild(b)})}
function hotList(){if(!S.scene){E.list.textContent='select background';return}let hs=S.scene.hotspots;if(!hs.length){E.list.textContent='no hotspots';return}E.list.innerHTML=hs.map((h,i)=>`<button class="hotspot-list-item${h.id===S.sel?' selected':''}" data-id="${esc(h.id)}"><strong>${i+1}. ${esc(h.id)}</strong><span>${esc(h.name)} 路 x:${h.x} y:${h.y} w:${h.w} h:${h.h}</span></button>`).join('');$$('[data-id]',E.list).forEach(b=>b.onclick=()=>select(b.dataset.id,true))}
function down(e){if(!S.scene||e.button!==0)return;metrics();let p=pt(e),box=e.target.closest?.('.hotspot-box'),handle=e.target.closest?.('.resize-handle');if(box){let h=find(box.dataset.hotspotId);if(!h)return;hist();select(h.id);e.preventDefault();E.wrap.setPointerCapture(e.pointerId);S.drag={start:p,orig:{...h},id:h.id};S.mode=handle?'resizing':'moving';return}hist();e.preventDefault();E.wrap.setPointerCapture(e.pointerId);let h={id:nextId(),name:'new hotspot',target_label:'',tooltip:'',x:Math.round(p.x),y:Math.round(p.y),w:1,h:1,enabled:true};S.scene.hotspots.push(h);S.drag={start:p,id:h.id};S.mode='drawing';select(h.id);dirty()}
function move(e){mouse(e);if(S.mode==='idle'||!S.drag)return;let p=pt(e),h=find(S.drag.id);if(!h)return;if(S.mode==='drawing'){h.x=Math.round(Math.min(S.drag.start.x,p.x));h.y=Math.round(Math.min(S.drag.start.y,p.y));h.w=Math.max(1,Math.round(Math.abs(p.x-S.drag.start.x)));h.h=Math.max(1,Math.round(Math.abs(p.y-S.drag.start.y)))}else if(S.mode==='moving'){let o=S.drag.orig;h.x=clamp(Math.round(o.x+p.x-S.drag.start.x),0,S.nw-h.w);h.y=clamp(Math.round(o.y+p.y-S.drag.start.y),0,S.nh-h.h)}else{let o=S.drag.orig;h.w=Math.max(1,Math.round(o.w+p.x-S.drag.start.x));h.h=Math.max(1,Math.round(o.h+p.y-S.drag.start.y))}fill(h);draw();hotList();dirty()}
function up(e){if(S.mode!=='idle'){try{E.wrap.releasePointerCapture(e.pointerId)}catch{}}let h=find(S.drag?.id);if(S.mode==='drawing'&&h&&(h.w<3||h.h<3))remove(h.id);S.mode='idle';S.drag=null;draw();hotList()}
function pt(e){let r=E.img.getBoundingClientRect(),dx=clamp(e.clientX-r.left,0,r.width),dy=clamp(e.clientY-r.top,0,r.height);return{x:dx*gx(),y:dy*gy()}}
function mouse(e){if(!S.bg||!S.dw){E.mouse.textContent='mouse:-';return}let p=pt(e);E.mouse.textContent=`mouse:${Math.round(p.x)},${Math.round(p.y)}`}
function select(id,focus=false){let h=find(id);if(!h)return;S.sel=id;fill(h);ui();draw();hotList();if(focus){let box=$(`.hotspot-box[data-hotspot-id="${CSS.escape(id)}"]`);box?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'})}}
function fill(h){E.hid.value=h?.id||'';E.id.value=h?.id||'';E.name.value=h?.name||'';E.target.value=h?.target_label||'';E.tip.value=h?.tooltip||'';E.x.value=h?.x??0;E.y.value=h?.y??0;E.w.value=h?.w??100;E.h.value=h?.h??100;E.enabled.checked=h?.enabled??true}
function syncForm(){let h=find(S.sel);if(!h)return;let old=h.id,nid=uniqueId(E.id.value.trim()||old,old);h.id=nid;h.name=E.name.value.trim()||'new hotspot';h.target_label=E.target.value.trim();h.tooltip=E.tip.value.trim();h.x=Math.max(0,num(E.x,h.x));h.y=Math.max(0,num(E.y,h.y));h.w=Math.max(1,num(E.w,h.w));h.h=Math.max(1,num(E.h,h.h));h.enabled=E.enabled.checked;S.sel=nid;fill(h);draw();hotList();dirty()}
function delSel(){if(!S.sel)return;hist();remove(S.sel);S.sel=null;fill(null);draw();hotList();dirty();ui()}
function dupSel(){let h=find(S.sel);if(!h)return;hist();let c={...h,id:nextId(),name:(h.name||'hotspot')+' copy',x:h.x+20,y:h.y+20};S.scene.hotspots.push(c);select(c.id,true);dirty()}
function moveLayer(d){if(!S.sel||!S.scene)return;let a=S.scene.hotspots,i=a.findIndex(h=>h.id===S.sel),j=i+d;if(i<0||j<0||j>=a.length)return;hist();[a[i],a[j]]=[a[j],a[i]];draw();hotList();dirty()}
async function save(){try{validate();setSave('saving');let r=await fetch('/api/hotspots/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(S.doc)}),j=await r.json();if(!r.ok)throw Error(j.detail||'save failed');S.doc=j;S.undo=[snap()];S.redo=[];setSave('saved');log('saved tools_data/hotspots.json')}catch(e){setSave('failed');log('save failed: '+e.message)}}
async function exportHotspots(){try{let c=await runChecks();if(c&&!c.ok)log('warning: hotspot check has issues before export');E.exportBtn.disabled=true;E.exportStatus.textContent='Export: exporting...';let r=await fetch('/api/export/hotspots',{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.detail||'export failed');E.exportStatus.textContent=`Export: ${j.scene_count} screens / ${j.hotspot_count} buttons`;log(`exported ${j.output_path}`)}catch(e){E.exportStatus.textContent='Export: failed';log('export failed: '+e.message)}finally{ui()}}
async function runChecks(){try{let r=await fetch('/api/hotspots/check'),j=await r.json();if(!r.ok)throw Error(j.detail||'check failed');renderCheck(j);dashHotspots(j.summary);let tr=await fetch('/api/hotspots/label-templates'),tj=await tr.json();if(tr.ok)renderTemplates(tj);log(`check: ok=${j.summary.ok} missing=${j.summary.missing} empty=${j.summary.empty} invalid=${j.summary.invalid} disabled=${j.summary.disabled}`);return j}catch(e){E.checkSummary.textContent='Check failed';E.checkList.textContent=e.message;log('check failed: '+e.message);return null}}
function renderCheck(j){let s=j.summary;E.checkSummary.textContent=`total ${s.total} / ok ${s.ok} / missing ${s.missing} / empty ${s.empty} / invalid ${s.invalid} / disabled ${s.disabled}`;E.checkList.classList.remove('empty');E.checkList.innerHTML=(j.items||[]).map(i=>`<div class="check-item ${i.status}"><strong>${esc(i.status)}</strong><span>${esc(i.hotspot_id)} -> ${esc(i.target_label||'(empty)')}</span><small>${esc(i.message)} 路 suggest: ${esc(i.suggested_label)}</small></div>`).join('')||'no hotspots'}
function renderTemplates(j){E.templatePreview.textContent=(j.templates||[]).map(t=>t.template).join('\n')||'No missing label templates.'}
async function inspectResources(){try{let r=await fetch('/api/resources/inspect'),j=await r.json();if(!r.ok)throw Error(j.detail||'resource inspect failed');S.resourceData=j;S.resourceSelected=null;renderResources(j);dashResources(j.summary);route('assets');log(`resources: total=${j.summary.total} naming=${j.summary.naming_warnings} missing=${j.summary.missing_references} unused=${j.summary.unused_resources}`);return j}catch(e){E.resourceSummary.textContent='Resource check failed';E.resourceStats.textContent=e.message;log('resource inspect failed: '+e.message);return null}}
function setResourceFilter(filter){S.resourceFilter=filter||'all';$$('[data-resource-filter]').forEach(b=>b.classList.toggle('active',b.dataset.resourceFilter===S.resourceFilter));if(S.resourceData)renderResourceList()}
function renderResources(j){let s=j.summary;E.resourceSummary.textContent=`total ${s.total} / naming ${s.naming_warnings} / missing ${s.missing_references} / unused ${s.unused_resources}`;E.resourceStats.classList.remove('empty');E.resourceStats.innerHTML=[['total','全部',s.total],['backgrounds','背景',s.backgrounds],['characters','角色',s.characters],['ui','UI',s.ui],['audio','音频',s.audio],['other_images','其他图片',s.other_images]].map(([k,t,v])=>`<button class="resource-stat-card" type="button" data-resource-filter="${k==='total'?'all':k}"><span>${t}</span><strong>${v}</strong></button>`).join('');$$('[data-resource-filter]',E.resourceStats).forEach(b=>b.onclick=()=>setResourceFilter(b.dataset.resourceFilter));renderResourceList();E.resourceNaming.innerHTML=renderResourceIssues(j.naming_issues);E.resourceMissing.innerHTML=(j.missing_references||[]).map(i=>`<button class="resource-item missing" type="button"><strong>${esc(i.reference)}</strong><small>${esc(i.file)}:${i.line}</small></button>`).join('')||'No missing references.';E.resourceUnused.innerHTML=(j.unused_resources||[]).slice(0,160).map(i=>renderResourceIssueResource(i.resource,'unused')).join('')||'No unused resources.';bindResourceButtons(E.resourceNaming);bindResourceButtons(E.resourceUnused)}
function renderResourceList(){let items=S.resourceData?.resources||[];if(S.resourceFilter!=='all')items=items.filter(r=>r.category===S.resourceFilter);if(E.resourceListCount)E.resourceListCount.textContent=`${items.length} items`;E.resourceList.classList.remove('empty');E.resourceList.innerHTML=items.map(r=>renderResourceRow(r)).join('')||'No resources.';bindResourceButtons(E.resourceList)}
function renderResourceRow(r){let sel=S.resourceSelected===r.relative_path?' selected':'';return`<button class="resource-row${sel}" type="button" data-resource-path="${esc(r.relative_path)}"><span class="resource-type ${esc(r.category)}">${esc(r.category)}</span><strong>${esc(r.name)}</strong><small>${esc(r.relative_path)}</small><em>${esc(r.extension)} · ${fmt(r.size_bytes)}</em></button>`}
function renderResourceIssues(items){return(items||[]).slice(0,160).map(i=>`<button class="resource-item warning" type="button" data-resource-path="${esc(i.resource.relative_path)}"><strong>${esc(i.code)}</strong><span>${esc(i.resource.relative_path)}</span><small>${esc(i.message)}</small></button>`).join('')||'No naming warnings.'}
function renderResourceIssueResource(r,cls){return`<button class="resource-item ${cls}" type="button" data-resource-path="${esc(r.relative_path)}"><strong>${esc(r.category)}</strong><span>${esc(r.relative_path)}</span><small>${fmt(r.size_bytes)}</small></button>`}
function bindResourceButtons(root){$$('[data-resource-path]',root).forEach(b=>b.onclick=()=>selectResource(b.dataset.resourcePath))}
function selectResource(path){let r=(S.resourceData?.resources||[]).find(x=>x.relative_path===path);if(!r)return;S.resourceSelected=path;renderResourceList();renderResourceDetail(r);if(r.is_image)previewResource(path)}
function renderResourceDetail(r){E.resourceDetail.classList.remove('empty');E.resourceDetail.innerHTML=`<div class="resource-detail-title"><strong>${esc(r.name)}</strong><span>${esc(r.category)}</span></div><dl><dt>路径</dt><dd>${esc(r.relative_path)}</dd><dt>类型</dt><dd>${esc(r.extension)}</dd><dt>大小</dt><dd>${fmt(r.size_bytes)}</dd><dt>图片</dt><dd>${r.is_image?'是':'否'}</dd></dl>`}
function previewResource(path){E.resourcePreview.classList.remove('empty');E.resourcePreview.innerHTML=`<img src="/api/assets/file?path=${encodeURIComponent(path)}" alt="resource preview"><small>${esc(path)}</small>`}
async function loadLabelGraph(){try{let r=await fetch('/api/labels/graph'),j=await r.json();if(!r.ok)throw Error(j.detail||'label graph failed');S.labelGraph=j;renderLabelGraph(j);route('labels');log(`labels: count=${j.summary.label_count} edges=${j.summary.edge_count} missing=${j.summary.missing_count} unused=${j.summary.unused_count}`);return j}catch(e){E.labelGraphSummary.textContent='Label graph failed';E.labelList.textContent=e.message;log('label graph failed: '+e.message);return null}}
function setLabelFilter(filter){S.labelFilter=filter||'all';$$('[data-label-filter]').forEach(b=>b.classList.toggle('active',b.dataset.labelFilter===S.labelFilter));renderLabelList();renderLabelGraphSvg()}
function setLabelStatusFilter(filter){S.labelStatusFilter=filter||'all';$$('[data-label-status]').forEach(b=>b.classList.toggle('active',b.dataset.labelStatus===S.labelStatusFilter));renderLabelList();renderLabelGraphSvg()}
function setLabelEdgeFilter(filter){S.labelEdgeFilter=filter||'all';$$('[data-edge-filter]').forEach(b=>b.classList.toggle('active',b.dataset.edgeFilter===S.labelEdgeFilter));if(S.labelGraph){E.labelEdges.innerHTML=filteredEdges(S.labelGraph.edges||[]).slice(0,180).map(renderEdge).join('')||'暂无跳转关系。';renderLabelGraphSvg();if(S.labelSelected)selectLabel(S.labelSelected)}}
function renderLabelGraph(j){let s=j.summary;E.labelGraphSummary.textContent=`labels ${s.label_count} / edges ${s.edge_count} / missing ${s.missing_count} / unused ${s.unused_count}`;E.labelHealthCards.classList.remove('empty');E.labelHealthCards.innerHTML=`<div><span>Label</span><strong>${s.label_count}</strong></div><div><span>Jump / Call</span><strong>${s.edge_count}</strong></div><div><span>死链</span><strong>${s.missing_count}</strong></div><div><span>动态</span><strong>${s.dynamic_count}</strong></div><div><span>可能未使用</span><strong>${s.unused_count}</strong></div>`;renderLabelList();E.labelEdges.innerHTML=filteredEdges(j.edges||[]).slice(0,180).map(renderEdge).join('')||'暂无跳转关系。';E.labelMissing.innerHTML=(j.missing||[]).map(renderEdge).join('')||'无死链。';E.labelUnused.innerHTML=(j.unused||[]).map(l=>`<button class="label-issue possibly-unused" type="button" data-label-name="${esc(l.name)}"><strong>${esc(l.name)}</strong><small>${esc(l.file)}:${l.line}</small></button>`).join('')||'无未使用 label。';$$('[data-label-name]',E.labelUnused).forEach(b=>b.onclick=()=>selectLabel(b.dataset.labelName));fitLabelGraph()}
function renderLabelList(){let labels=visibleLabels();E.labelList.classList.remove('empty');E.labelList.innerHTML=labels.map(l=>`<button class="label-row ${l.status}${S.labelSelected===l.name?' selected':''}" type="button" data-label-name="${esc(l.name)}"><strong>${esc(l.name)}</strong><span>${esc(labelCategory(l.category))} · in ${l.incoming_count} / out ${l.outgoing_count}</span><small>${esc(l.file)}:${l.line}</small></button>`).join('')||'没有匹配的 label。';$$('[data-label-name]',E.labelList).forEach(b=>b.onclick=()=>selectLabel(b.dataset.labelName))}
function renderEdge(e){return`<div class="label-edge ${esc(e.status)}"><strong>${esc(e.from_label)} → ${esc(e.to_label)}</strong><span>${esc(e.type)} · ${esc(e.status)}</span><small>${esc(e.file)}:${e.line}</small></div>`}
async function selectLabel(name){S.labelSelected=name;renderLabelList();renderLabelGraphSvg();try{let r=await fetch('/api/labels/detail?name='+encodeURIComponent(name)),j=await r.json();if(!r.ok||!j.ok)throw Error('label not found');S.labelDetail=j;renderLabelDetail(j)}catch(e){E.labelDetail.textContent=e.message}}
function renderLabelDetail(j){let l=j.label,inc=filteredEdges(j.incoming),out=filteredEdges(j.outgoing);E.labelDetail.classList.remove('empty');E.labelDetail.innerHTML=`<div class="label-detail-title"><strong>${esc(l.name)}</strong><span>${esc(labelCategory(l.category))} · ${esc(l.status)}</span></div><dl><dt>文件</dt><dd>${esc(l.file)}:${l.line}</dd><dt>入边</dt><dd>${j.incoming.length}</dd><dt>出边</dt><dd>${j.outgoing.length}</dd><dt>热区</dt><dd>${j.hotspots.length}</dd><dt>Unused</dt><dd>${l.status==='possibly_unused'?'是':'否'}</dd><dt>Hotspot</dt><dd>${j.hotspots.length?'是':'否'}</dd></dl><h3>Incoming</h3>${inc.map(renderEdge).join('')||'<p class="muted">无</p>'}<h3>Outgoing</h3>${out.map(renderEdge).join('')||'<p class="muted">无</p>'}<h3>关联热区</h3>${j.hotspots.map(h=>`<div class="label-hotspot"><strong>${esc(h.hotspot_id)}</strong><span>${esc(h.hotspot_name)} · ${esc(h.scene_id)}</span></div>`).join('')||'<p class="muted">无</p>'}`;renderFixSuggestions(j)}
function renderFixSuggestions(j){let l=j.label,parts=[];let missing=(S.labelGraph?.missing||[]).filter(e=>e.from_label===l.name||e.to_label===l.name);let dynamic=(S.labelGraph?.edges||[]).filter(e=>e.status==='dynamic'&&(e.from_label===l.name||e.to_label===l.name));if(missing.length)parts.push('<h3>Missing link</h3><p>问题：jump/call 指向不存在的 label。建议：新增目标 label、修改 jump/call 目标；如果是动态跳转，改为 jump expression。</p>');if(dynamic.length)parts.push('<h3>Dynamic link</h3><p>问题：jump expression / call screen 无法静态确认。建议：人工确认目标、注释预期目标；如可固定，改为普通 jump/call。</p>');if(l.status==='possibly_unused')parts.push('<h3>Possibly unused</h3><p>问题：该 label 没有静态入边。建议：确认是否由菜单/外部/动态调用；测试入口保留；废弃节点标记待清理。</p>');if(j.hotspots.length)parts.push('<h3>Hotspot linked</h3><p>说明：该 label 被热点引用。建议：不要随意删除；修改 label 名时同步更新 hotspots.json。</p>');if(!parts.length)parts.push('<p class="muted">当前未发现需要处理的问题。</p>');E.labelFixSuggestions.classList.remove('empty');E.labelFixSuggestions.innerHTML=parts.join('')}
function labelCategory(c){return {story:'正式剧情',test:'测试',investigation:'调查',system:'系统',unknown:'未知'}[c]||c}
function visibleLabels(){let labels=S.labelGraph?.labels||[];if(S.labelFilter!=='all')labels=labels.filter(l=>l.category===S.labelFilter);if(S.labelStatusFilter!=='all')labels=labels.filter(labelStatusPredicate);if(S.labelNeighborMode&&S.labelSelected)labels=labels.filter(l=>neighborNames().has(l.name));if(S.labelSearch)labels=labels.filter(l=>l.name.toLowerCase().includes(S.labelSearch));return labels.slice(0,80)}
function labelStatusPredicate(l){if(S.labelStatusFilter==='ok')return l.status==='ok'&&!hasHotspot(l.name);if(S.labelStatusFilter==='possibly_unused')return l.status==='possibly_unused';if(S.labelStatusFilter==='hotspot_linked')return hasHotspot(l.name);if(S.labelStatusFilter==='missing')return (S.labelGraph?.missing||[]).some(e=>e.from_label===l.name||e.to_label===l.name);if(S.labelStatusFilter==='dynamic')return (S.labelGraph?.edges||[]).some(e=>e.status==='dynamic'&&(e.from_label===l.name||e.to_label===l.name));return true}
function hasHotspot(name){return Boolean((S.labelGraph?.labels||[]).find(l=>l.name===name)?.hotspot_count)}
function neighborNames(){let set=new Set([S.labelSelected]);(S.labelGraph?.edges||[]).forEach(e=>{if(e.from_label===S.labelSelected)set.add(e.to_label);if(e.to_label===S.labelSelected)set.add(e.from_label)});return set}
function filteredEdges(edges){return (edges||[]).filter(e=>S.labelEdgeFilter==='all'||e.type===S.labelEdgeFilter||e.status===S.labelEdgeFilter)}
function graphGroups(nodes,height){let meta={system:'System',story:'Story / Chapter',investigation:'Investigation',test:'Test',unknown:'Unknown'},by={};nodes.forEach(n=>{let g=by[n.category]||={key:n.category,title:meta[n.category]||n.category,x:n.x,count:0,maxY:120};g.count++;g.maxY=Math.max(g.maxY,n.y)});return Object.values(by)}
function layoutLabelNodes(){let labels=visibleLabels(),order=['system','story','investigation','test','unknown'],cols={};order.forEach((c,i)=>cols[c]={x:120+i*220,items:[]});labels.forEach(l=>(cols[l.category]||cols.unknown).items.push(l));let nodes=[];Object.values(cols).forEach(col=>col.items.sort((a,b)=>a.file===b.file?a.line-b.line:a.file.localeCompare(b.file)).forEach((l,i)=>nodes.push({...l,x:col.x,y:90+i*86})));S.labelGraphNodes=nodes;return nodes}
function renderLabelGraphSvg(){if(!E.labelGraphSvg||!S.labelGraph)return;let nodes=layoutLabelNodes(),map=new Map(nodes.map(n=>[n.name,n]));let edges=filteredEdges(S.labelGraph.edges||[]).filter(e=>map.has(e.from_label)&&map.has(e.to_label)).slice(0,220);let width=Math.max(1100,...nodes.map(n=>n.x+180)),height=Math.max(620,...nodes.map(n=>n.y+80));if(E.labelGraphVisible)E.labelGraphVisible.textContent=`${nodes.length} nodes / ${edges.length} edges`;let groups=graphGroups(nodes,height);let groupSvg=groups.map(g=>`<g class="graph-group ${esc(g.key)}"><rect x="${g.x-100}" y="28" width="200" height="${Math.max(170,g.maxY+70)}" rx="18"></rect><text x="${g.x-86}" y="54">${esc(g.title)} · ${g.count}</text></g>`).join('');let selected=S.labelSelected;let related=selected?neighborNames():null;let edgeSvg=edges.map(e=>{let a=map.get(e.from_label),b=map.get(e.to_label),mx=(a.x+b.x)/2,rel=!selected||e.from_label===selected||e.to_label===selected;return`<path class="graph-edge ${esc(e.status)} ${esc(e.type)}${rel?' related':' dim'}" d="M ${a.x+76} ${a.y} C ${mx} ${a.y}, ${mx} ${b.y}, ${b.x-76} ${b.y}"><title>${esc(e.from_label)} → ${esc(e.to_label)} · ${esc(e.type)} · ${esc(e.status)}</title></path>`}).join('');let nodeSvg=nodes.map(n=>{let rel=!selected||related.has(n.name);let cls=`graph-node ${esc(n.category)} ${esc(n.status)}${S.labelSelected===n.name?' selected':''}${S.labelSearch&&n.name.toLowerCase().includes(S.labelSearch)?' search-hit':''}${hasHotspot(n.name)?' hotspot-linked':''}${rel?' related':' dim'}`;return`<g class="${cls}" data-label-name="${esc(n.name)}" transform="translate(${n.x-76},${n.y-28})"><rect width="152" height="56" rx="14"></rect><text x="12" y="24">${esc(n.name).slice(0,18)}</text><text class="meta" x="12" y="42">${esc(labelCategory(n.category))} · ${n.incoming_count}/${n.outgoing_count} · H${n.hotspot_count||0}</text><title>${esc(n.name)} · ${esc(n.file)}:${n.line}</title></g>`}).join('');E.labelGraphSvg.setAttribute('viewBox',`${-S.labelGraphPan.x} ${-S.labelGraphPan.y} ${Math.max(400,width/S.labelGraphZoom)} ${Math.max(300,height/S.labelGraphZoom)}`);E.labelGraphSvg.innerHTML=`<g>${groupSvg}${edgeSvg}${nodeSvg}</g>`;$$('[data-label-name]',E.labelGraphSvg).forEach(n=>n.onclick=e=>{e.stopPropagation();selectLabel(n.dataset.labelName)})}
function fitLabelGraph(){S.labelGraphZoom=1;S.labelGraphPan={x:0,y:0};renderLabelGraphSvg()}
function zoomLabelGraph(f){S.labelGraphZoom=Math.max(.45,Math.min(2.4,S.labelGraphZoom*f));renderLabelGraphSvg()}
function startLabelGraphPan(e){if(e.button!==0)return;S.labelGraphDrag={x:e.clientX,y:e.clientY,pan:{...S.labelGraphPan}};E.labelGraphCanvas.setPointerCapture?.(e.pointerId)}
function moveLabelGraphPan(e){if(!S.labelGraphDrag)return;S.labelGraphPan={x:S.labelGraphDrag.pan.x+(e.clientX-S.labelGraphDrag.x)/S.labelGraphZoom,y:S.labelGraphDrag.pan.y+(e.clientY-S.labelGraphDrag.y)/S.labelGraphZoom};renderLabelGraphSvg()}
function endLabelGraphPan(e){if(S.labelGraphDrag){try{E.labelGraphCanvas.releasePointerCapture?.(e.pointerId)}catch{}S.labelGraphDrag=null}}
function validate(){for(let sc of S.doc.scenes){if(!sc.background||sc.background.includes('..')||/^[a-zA-Z]:/.test(sc.background))throw Error('bad background');let ids=new Set;for(let h of sc.hotspots){if(!h.id)throw Error('empty id');if(ids.has(h.id))throw Error('duplicate id '+h.id);ids.add(h.id);if(![h.x,h.y,h.w,h.h].every(Number.isFinite))throw Error('bad coords');if(h.w<=0||h.h<=0)throw Error('bad size')}}}
function hist(){let s=snap();if(S.undo[S.undo.length-1]!==s){S.undo.push(s);if(S.undo.length>80)S.undo.shift()}S.redo=[];ui()}
function snap(){return JSON.stringify({doc:S.doc,bg:S.bg,sel:S.sel})}
function restore(s){let o=JSON.parse(s);S.doc=o.doc;S.bg=o.bg;S.sel=o.sel;S.scene=S.bg?scene(S.bg):null;if(S.bg){E.img.src='/api/assets/file?path='+encodeURIComponent(S.bg);E.bgName.textContent=S.bg}fill(find(S.sel));draw();hotList();ui();dirty()}
function undo(){if(S.undo.length<2)return;S.redo.push(S.undo.pop());restore(S.undo[S.undo.length-1]);log('undo')}
function redo(){if(!S.redo.length)return;let s=S.redo.pop();S.undo.push(s);restore(s);log('redo')}
function keys(e){if(e.ctrlKey&&(e.key==='+'||e.key==='=')){e.preventDefault();setZoom(S.zoom+.25,true)}else if(e.ctrlKey&&e.key==='-'){e.preventDefault();setZoom(S.zoom-.25,true)}else if(e.ctrlKey&&e.key==='0'){e.preventDefault();setZoom(1,true)}else if(e.ctrlKey&&e.key.toLowerCase()==='z'&&e.shiftKey){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='d'){e.preventDefault();dupSel()}else if(e.key==='Delete'){e.preventDefault();delSel()}else if(e.key==='Escape'){S.sel=null;fill(null);draw();hotList();ui()}}
function find(id){return id&&S.scene?S.scene.hotspots.find(h=>h.id===id):null}
function remove(id){if(S.scene)S.scene.hotspots=S.scene.hotspots.filter(h=>h.id!==id)}
function nextId(){return uniqueId('hotspot_'+String((S.scene?.hotspots.length||0)+1).padStart(3,'0'))}
function uniqueId(base,allow=null){let ids=new Set((S.scene?.hotspots||[]).map(h=>h.id));let b=base||'hotspot';if(!ids.has(b)||b===allow)return b;let i=2;while(ids.has(`${b}_${i}`))i++;return `${b}_${i}`}
function dirty(){S.dirty=true;setSave('unsaved');ui()}
function setSave(v){S.save=v;S.dirty=v==='unsaved';E.saveStatus.className='save-status '+v;E.saveStatus.textContent={saved:'Saved',unsaved:'Unsaved',saving:'Saving...',failed:'Save failed'}[v]||v;ui()}
function ui(){let has=!!S.sel,scene=!!S.scene;E.save.disabled=!scene;E.checkBtn.disabled=!S.projectPath;E.inspectBtn.disabled=!S.projectPath;E.exportBtn.disabled=!S.projectPath;E.apply.disabled=!has;E.del.disabled=!has;E.dup.disabled=!has;E.up.disabled=!has;E.down.disabled=!has;E.undo.disabled=S.undo.length<2;E.redo.disabled=!S.redo.length;E.save.textContent=S.save==='unsaved'?'保存 hotspots.json *':'保存 hotspots.json'}
function row(a,b){return `<div class="status-row"><span>${a}</span><strong>${b}</strong></div>`}
function badge(v){return `<span class="badge ${v?'ok':'bad'}">${v?'OK':'MISS'}</span>`}
function log(t){E.log.textContent=`${E.log.textContent}\n${t}`.trim()}
function setLoad(v){E.scan.disabled=v;E.scan.textContent=v?'扫描中...':'扫描项目'}
function gx(){return S.dw?S.nw/S.dw:1}function gy(){return S.dh?S.nh/S.dh:1}
function num(i,f){let v=Number(i.value);return Number.isFinite(v)?Math.round(v):f}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function fmt(n){if(!Number.isFinite(n)||n<=0)return'0 B';let u=['B','KB','MB','GB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}


