"""Export hotspot JSON to a standalone Ren'Py screen file.

V0.2b only writes:
    <project>/game/generated_hotspots.rpy
It never modifies script.rpy/gui.rpy/options.rpy or any asset directory.
"""

from __future__ import annotations

from pathlib import Path

from .hotspot_manager import load_hotspots
from .models import ExportResult, HotspotDocument, SceneHotspots

EXPORT_RELATIVE_PATH = Path("game") / "generated_hotspots.rpy"


def export_hotspots(project_path: Path) -> ExportResult:
    """Export tools_data/hotspots.json to game/generated_hotspots.rpy."""

    document = load_hotspots(project_path)
    output_path = project_path / EXPORT_RELATIVE_PATH
    _ensure_safe_output_path(project_path, output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = render_generated_hotspots(document)
    output_path.write_text(content, encoding="utf-8")

    enabled_count = sum(1 for scene in document.scenes for hotspot in scene.hotspots if hotspot.enabled)
    skipped_count = sum(1 for scene in document.scenes for hotspot in scene.hotspots if not hotspot.enabled)
    return ExportResult(
        ok=True,
        output_path=str(output_path),
        screens=[f"hotspots_{scene.scene_id}" for scene in document.scenes],
        scene_count=len(document.scenes),
        hotspot_count=enabled_count,
        skipped_count=skipped_count,
        message="Exported Ren'Py hotspot screens.",
    )


def render_generated_hotspots(document: HotspotDocument) -> str:
    lines: list[str] = [
        "# AUTO-GENERATED by AVGBuilder V0.2b.",
        "# Source: tools_data/hotspots.json",
        "# Do not edit by hand unless you know what you are doing.",
        "",
    ]
    if not document.scenes:
        lines.extend(["# No scenes found.", ""])
        return "\n".join(lines)

    for scene in document.scenes:
        lines.extend(_render_scene_screen(scene))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_scene_screen(scene: SceneHotspots) -> list[str]:
    screen_name = _safe_identifier(f"hotspots_{scene.scene_id}")
    lines = [
        f"screen {screen_name}():",
        f"    # background: {scene.background}",
    ]
    enabled_hotspots = [hotspot for hotspot in scene.hotspots if hotspot.enabled]
    if not enabled_hotspots:
        lines.append("    pass")
        return lines

    for hotspot in enabled_hotspots:
        action = f'Jump("{_escape_string(hotspot.target_label)}")' if hotspot.target_label else "NullAction()"
        tooltip = hotspot.tooltip or ""
        lines.extend(
            [
                f"    # hotspot: {hotspot.id} | {hotspot.name}",
                f"    # tooltip: {_escape_comment(tooltip)}",
                "    imagebutton:",
                "        idle Solid(\"#00000000\")",
                "        hover Solid(\"#FFD96655\")",
                f"        xpos {int(hotspot.x)}",
                f"        ypos {int(hotspot.y)}",
                f"        xsize {int(hotspot.w)}",
                f"        ysize {int(hotspot.h)}",
                f"        action {action}",
                "",
            ]
        )
    if lines[-1] == "":
        lines.pop()
    return lines


def _safe_identifier(value: str) -> str:
    result = "".join(char if char.isalnum() or char == "_" else "_" for char in value)
    if not result or result[0].isdigit():
        result = f"_{result}"
    return result


def _escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _escape_comment(value: str) -> str:
    return value.replace("\n", " ").replace("\r", " ")


def _ensure_safe_output_path(project_path: Path, output_path: Path) -> None:
    expected = (project_path / EXPORT_RELATIVE_PATH).resolve(strict=False)
    actual = output_path.resolve(strict=False)
    if actual != expected:
        raise ValueError(f"Refusing to write outside allowed export file: {actual}")
